import localFont from "next/font/local";
import Layout from "./components/Layout";
import './styles/globals.css';
import { AuthProvider } from './components/AuthProvider';
import Script from 'next/script';
import GoogleApiInitializer from './components/GoogleApiInitializer';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "ClassQuest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet-routing-machine@3.2.12/dist/leaflet-routing-machine.css"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Layout>{children}</Layout>
          <GoogleApiInitializer />
        </AuthProvider>
        <Script 
          src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          strategy="afterInteractive"
        />
        <Script 
          src="https://unpkg.com/leaflet-routing-machine@3.2.12/dist/leaflet-routing-machine.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}